sudo: false
language: java
jdk:
- oraclejdk7
env:
  global:
  - secure: IE/mfL1X/GtHnU5HtxL24u/SSkoTXnBBHbtfIpyjYwgbzGhPuq9qn9nEOBNb43ePaPGO+PDMz9sxDxHSIwBgbomEmq3dvQ9j+2jOx7MhmtCVr8Jz9x0xhug4cVPhaMVUZDa+z3qfSzbDbdtRKvuAzWHhwnbS9gQaGn1oIR2++5tXGZk+LVyvDO5/wbR6EcMxDQf0ZmUde/q0QtDmkIinS5r09ydUhsJE1wCUzyiOhx/kErnGmGD6buI/AgiZeGsGouonCykjrlNkoZkgmHobu/eCfbZPxUY9AkoJxORiLXZQ4GYH3KAvJlo5OZo99W8nw7wgnKZLJVkQD/sZzz3BCNlFQj41MroGUECm+fAq1hCDkXM1AmyFj9ZDQGyeb5+uEhf37mCN0TnUP6PNTTr+g/CqhQK67GDXM0i8LLKpEa/KtRuTtYm+gQ1VWJFYnxTx121XpEW8RKooqMbnBtOGngZqDqYb/8UjXg97logHThPMzpx3pkmDKlI+eB6wKi8VuBcMMIMU7K/pqUyWMqjK+JTAorPHJH17pCywsqsw0XghrIxjBjfTi7v8i9JxmV+9IadiaHhBj1WxJT3WnNEt7WEp4Q0ZxAL5ToiHT25ga55+9MHP9rJnqyunXon0q6MUoO3ubUmHU3wukCbakvZb7h8fEuCtMdzfA0TIZ7EsDIE=
  - secure: KgQpjq/B3jLeEX1yaOWDQwYtIhPLtxsjbme83W740/bWBqjJ28NOmHeiwXzN2hw4pVMpz4LXn1jgB6Z38W91xsLsUsM5fINiaS27Q87VOE7B8fbJT5KImExFOcERdFqoCLtz4q2GA6DKbzbe8a5n9WkZT/EpuIPNgVtjlMtOP9K3A9+iuIPpbLgyE+j+LNQJINzxJE9BrN3qasTsD3wHQe7ZjEaUgYLHs/U+IbHXBG2IP4uXWMgk33BpNAK10E9H7W3xk4vIcFsvB5sLjpjKD/4mD1Ltmm/gkl3DwNEVmOxcDXCHHH5X0Rcf2gb41AbqiyUOs6Au/lkPF1lX+6bFsFF/gTIVuXxv3K3zUmRlRsdsd7HoAXp0sP/9GwrDs8ps/8MVPoaWKZu4IkNNPWBVboGRQmmGg5043mAyKhKYh/hygKgcHQpi8x4N7KNozLmbEagttbait66E87JAZNozGOKjEsK0G3Mvx64ISI9xmsIzPeqfLJDLkfnUAMODeR+JSYlTs1jYy3VPlx9X6uBGO6+qcySPZ7F/WAUgna1UwjVhbZM/hZoJU/1auYtpxiDOPm/ogHA/oleDALaO0cP1lqp6bV9PO/1/hpJWm/PG0C813UelykaF4VPqMmMR1C9Ob/GUzgpXB5rYjJKsPAVeiu093tkVNsjJ/rrmMmV2Tj0=
after_success:
- "./gradlew coveralls -PisCI"
- "./gradlew bintrayUpload"
cache:
  directories:
  - "$HOME/.gradle/wrapper"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/caches/2.6"
  - "$HOME/.gradle/caches/modules-2/files-2.1"
  - "$HOME/.gradle/caches/modules-2/metadata-2.15"
